#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v17
# autospec commit: b5caddc
#
Name     : R-tidytable
Version  : 0.11.1
Release  : 2
URL      : https://cran.r-project.org/src/contrib/tidytable_0.11.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tidytable_0.11.1.tar.gz
Summary  : Tidy Interface to 'data.table'
Group    : Development/Tools
License  : MIT
Requires: R-data.table
Requires: R-glue
Requires: R-lifecycle
Requires: R-magrittr
Requires: R-pillar
Requires: R-rlang
Requires: R-tidyselect
Requires: R-vctrs
BuildRequires : R-data.table
BuildRequires : R-glue
BuildRequires : R-lifecycle
BuildRequires : R-magrittr
BuildRequires : R-pillar
BuildRequires : R-rlang
BuildRequires : R-tidyselect
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
giving users the speed of 'data.table' while using tidyverse-like syntax.

%prep
%setup -q -n tidytable

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721751973

%install
export SOURCE_DATE_EPOCH=1721751973
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tidytable/DESCRIPTION
/usr/lib64/R/library/tidytable/INDEX
/usr/lib64/R/library/tidytable/LICENSE
/usr/lib64/R/library/tidytable/Meta/Rd.rds
/usr/lib64/R/library/tidytable/Meta/features.rds
/usr/lib64/R/library/tidytable/Meta/hsearch.rds
/usr/lib64/R/library/tidytable/Meta/links.rds
/usr/lib64/R/library/tidytable/Meta/nsInfo.rds
/usr/lib64/R/library/tidytable/Meta/package.rds
/usr/lib64/R/library/tidytable/NAMESPACE
/usr/lib64/R/library/tidytable/NEWS.md
/usr/lib64/R/library/tidytable/R/tidytable
/usr/lib64/R/library/tidytable/R/tidytable.rdb
/usr/lib64/R/library/tidytable/R/tidytable.rdx
/usr/lib64/R/library/tidytable/help/AnIndex
/usr/lib64/R/library/tidytable/help/aliases.rds
/usr/lib64/R/library/tidytable/help/figures/logo.png
/usr/lib64/R/library/tidytable/help/paths.rds
/usr/lib64/R/library/tidytable/help/tidytable.rdb
/usr/lib64/R/library/tidytable/help/tidytable.rdx
/usr/lib64/R/library/tidytable/html/00Index.html
/usr/lib64/R/library/tidytable/html/R.css
/usr/lib64/R/library/tidytable/tests/testthat.R
/usr/lib64/R/library/tidytable/tests/testthat/test-across.R
/usr/lib64/R/library/tidytable/tests/testthat/test-add_count.R
/usr/lib64/R/library/tidytable/tests/testthat/test-arrange.R
/usr/lib64/R/library/tidytable/tests/testthat/test-as_tidytable.R
/usr/lib64/R/library/tidytable/tests/testthat/test-between.R
/usr/lib64/R/library/tidytable/tests/testthat/test-bind.R
/usr/lib64/R/library/tidytable/tests/testthat/test-case.R
/usr/lib64/R/library/tidytable/tests/testthat/test-case_match.R
/usr/lib64/R/library/tidytable/tests/testthat/test-case_when.R
/usr/lib64/R/library/tidytable/tests/testthat/test-coalesce.R
/usr/lib64/R/library/tidytable/tests/testthat/test-complete.R
/usr/lib64/R/library/tidytable/tests/testthat/test-consecutive_id.R
/usr/lib64/R/library/tidytable/tests/testthat/test-count.R
/usr/lib64/R/library/tidytable/tests/testthat/test-cumulative.R
/usr/lib64/R/library/tidytable/tests/testthat/test-cur-context.R
/usr/lib64/R/library/tidytable/tests/testthat/test-deprec-across.R
/usr/lib64/R/library/tidytable/tests/testthat/test-distinct.R
/usr/lib64/R/library/tidytable/tests/testthat/test-drop_na.R
/usr/lib64/R/library/tidytable/tests/testthat/test-dt.R
/usr/lib64/R/library/tidytable/tests/testthat/test-enframe.R
/usr/lib64/R/library/tidytable/tests/testthat/test-expand.R
/usr/lib64/R/library/tidytable/tests/testthat/test-expand_grid.R
/usr/lib64/R/library/tidytable/tests/testthat/test-extract.R
/usr/lib64/R/library/tidytable/tests/testthat/test-fill.R
/usr/lib64/R/library/tidytable/tests/testthat/test-filter.R
/usr/lib64/R/library/tidytable/tests/testthat/test-first-last-nth.R
/usr/lib64/R/library/tidytable/tests/testthat/test-fread.R
/usr/lib64/R/library/tidytable/tests/testthat/test-get_dummies.R
/usr/lib64/R/library/tidytable/tests/testthat/test-group_by.R
/usr/lib64/R/library/tidytable/tests/testthat/test-group_split.R
/usr/lib64/R/library/tidytable/tests/testthat/test-if_all-if_any.R
/usr/lib64/R/library/tidytable/tests/testthat/test-if_else.R
/usr/lib64/R/library/tidytable/tests/testthat/test-in-notin.R
/usr/lib64/R/library/tidytable/tests/testthat/test-join.R
/usr/lib64/R/library/tidytable/tests/testthat/test-lag-lead.R
/usr/lib64/R/library/tidytable/tests/testthat/test-mutate.R
/usr/lib64/R/library/tidytable/tests/testthat/test-mutate_rowwise.R
/usr/lib64/R/library/tidytable/tests/testthat/test-n_distinct.R
/usr/lib64/R/library/tidytable/tests/testthat/test-na_if.R
/usr/lib64/R/library/tidytable/tests/testthat/test-nest.R
/usr/lib64/R/library/tidytable/tests/testthat/test-nest_by.R
/usr/lib64/R/library/tidytable/tests/testthat/test-new_tidytable.R
/usr/lib64/R/library/tidytable/tests/testthat/test-pick.R
/usr/lib64/R/library/tidytable/tests/testthat/test-pivot_longer.R
/usr/lib64/R/library/tidytable/tests/testthat/test-pivot_wider.R
/usr/lib64/R/library/tidytable/tests/testthat/test-pull.R
/usr/lib64/R/library/tidytable/tests/testthat/test-purrr.R
/usr/lib64/R/library/tidytable/tests/testthat/test-rank.R
/usr/lib64/R/library/tidytable/tests/testthat/test-recode.R
/usr/lib64/R/library/tidytable/tests/testthat/test-reframe.R
/usr/lib64/R/library/tidytable/tests/testthat/test-relocate.R
/usr/lib64/R/library/tidytable/tests/testthat/test-rename.R
/usr/lib64/R/library/tidytable/tests/testthat/test-replace_na.R
/usr/lib64/R/library/tidytable/tests/testthat/test-rowwise.R
/usr/lib64/R/library/tidytable/tests/testthat/test-select.R
/usr/lib64/R/library/tidytable/tests/testthat/test-separate.R
/usr/lib64/R/library/tidytable/tests/testthat/test-separate_longer_delim.R
/usr/lib64/R/library/tidytable/tests/testthat/test-separate_rows.R
/usr/lib64/R/library/tidytable/tests/testthat/test-separate_wider_delim.R
/usr/lib64/R/library/tidytable/tests/testthat/test-separate_wider_regex.R
/usr/lib64/R/library/tidytable/tests/testthat/test-slice-head-tail.R
/usr/lib64/R/library/tidytable/tests/testthat/test-slice-min-max.R
/usr/lib64/R/library/tidytable/tests/testthat/test-slice.R
/usr/lib64/R/library/tidytable/tests/testthat/test-slice_sample.R
/usr/lib64/R/library/tidytable/tests/testthat/test-summarize.R
/usr/lib64/R/library/tidytable/tests/testthat/test-tidytable.R
/usr/lib64/R/library/tidytable/tests/testthat/test-top_n.R
/usr/lib64/R/library/tidytable/tests/testthat/test-transmute.R
/usr/lib64/R/library/tidytable/tests/testthat/test-tribble.R
/usr/lib64/R/library/tidytable/tests/testthat/test-uncount.R
/usr/lib64/R/library/tidytable/tests/testthat/test-unite.R
/usr/lib64/R/library/tidytable/tests/testthat/test-unnest.R
/usr/lib64/R/library/tidytable/tests/testthat/test-unnest_longer.R
/usr/lib64/R/library/tidytable/tests/testthat/test-unnest_wider.R
/usr/lib64/R/library/tidytable/tests/testthat/test-vctrs-tidytable.R
